"""Criando tabelas passageiro, voo e aeronave

Revision ID: 5bdb4c63a997
Revises: 
Create Date: 2026-08-29 12:13:33.380703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bdb4c63a997'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aeronaves',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('capacidade_assentos', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passageiros',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('voos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aeronave_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['aeronave_id'], ['aeronaves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voo_passageiro',
    sa.Column('voo_id', sa.String(length=36), nullable=False),
    sa.Column('passageiro_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['passageiro_id'], ['passageiros.id'], ),
    sa.ForeignKeyConstraint(['voo_id'], ['voos.id'], ),
    sa.PrimaryKeyConstraint('voo_id', 'passageiro_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voo_passageiro')
    op.drop_table('voos')
    op.drop_table('passageiros')
    op.drop_table('aeronaves')
    # ### end Alembic commands ###
